version: 1.x-{build}
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: ''
  package_version: 1.0.0.0-build{build}
environment:
  WEBHOOK_URL:
    secure: p3nnkhnWtqFFH8UJ1eaKFfRjFPlOVhNtmLjd94R7+KTpkKNbysGuec/79VzLBNYG4fP/ep8I026CFaMaFFQ6TMAxewnekvMojyHY4YGeOQcwDRwmdBNzygAllTwNsND3ThcpJYljaBoYT9gbSigZESCgktjtl0Uc1lUhQCAQdOM=
before_build:
- cmd: nuget restore "%APPVEYOR_BUILD_FOLDER%\Namer.sln"
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a devbuild.zip "%APPVEYOR_BUILD_FOLDER%\Namer\bin\Debug\"

    7z a devbuild-console.zip "%APPVEYOR_BUILD_FOLDER%\Namer.Demo\bin\Debug\"
artifacts:
- path: devbuild.zip
  name: Development build of Namer
- path: devbuild-console.zip
  name: Development build of Namer - Names Demo
- path: Namer/bin/Debug/*.nupkg
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 2ocxItByklPOySTf0USeSC6NpQGHHkhYMzj08PlSKNZE/VxLSLzcQpdt4VMTQnJI
  symbol_server: https://www.nuget.org/api/v2/package
on_success:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 failure $env:WEBHOOK_URL
